Removing unused files wc68.ko and wlc98_driver.ko
pick_prebuilt fails with the following error

  ERROR: wc68.ko has a version of 10291363, expecting 10297982.
  ERROR: wlc98_driver.ko has a version of 10291363, expecting 10297982.

cmd used for removing all unused files:
  find . -name wc68.ko -o -name wlc98_driver.ko -o -name "*_wc68_ko.asciipb" -o -name "*_wlc98_driver_ko.asciipb" | xargs rm

  sed -ri '/.+wc68.ko|.+wlc98_driver.ko/d' ./*.load ./*/*.load

Bug: 284522056

Change-Id: I8de6ee6d806723392b282ab3a78dd58b95e62a56
Signed-off-by: Neela Chithirala <chithiralan@google.com>