Remove pkvm-s2mpu.ko files due to not in use.
ERROR: pkvm-s2mpu.ko has a version of 9919448, expecting 9924255.

Bug: 277861200
Change-Id: Idc0a592bfd87a09f99d08c8e670a2404653dc311