Remove trusty-irq.ko files due to not in use.
ERROR: trusty-irq.ko has a version of 10024584, expecting 10029123.

Bug: 280013450
Change-Id: I5a8ed7813a0b02a7fbcb180dd02339537872e553
Signed-off-by: irischen <irischen@google.com>